version: "3.9"
services:
  api:
    build: 
      context: ../..
      dockerfile: docker/development/Dockerfile
    container_name: plant-system-api
    volumes:
      - ../..:/app
    restart: always
    env_file: ../../.env