// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/middleware/interface/middleware.go

// Package mock_middlewareitf is a generated GoMock package.
package mock_middlewareitf

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// AskPump mocks base method.
func (m *MockMiddleware) AskPump(next echo.HandlerFunc) echo.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskPump", next)
	ret0, _ := ret[0].(echo.HandlerFunc)
	return ret0
}

// AskPump indicates an expected call of AskPump.
func (mr *MockMiddlewareMockRecorder) AskPump(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskPump", reflect.TypeOf((*MockMiddleware)(nil).AskPump), next)
}
